package storage

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"

	"github.com/miaoxiaoyong/sift/internal/command"
)

func (d *DB) startupStallRetryRequestTx(ctx context.Context, tx *sql.Tx, env command.CommandEventEnvelopeV1, c command.CompiledCommandV1, row *commandInterruptRow, nowMS int64) (string, string, error) {
	if row == nil || row.AttemptNo < 1 || row.Generation < 1 {
		return "", "", ErrRejectedStale
	}
	nextNonce := newToken()
	res, err := tx.ExecContext(ctx, `UPDATE interrupts SET nonce=?,version=version+1,dispatch_state='probe_in_progress',held_reason=NULL,nonce_issued_at_ms=?,updated_at_ms=? WHERE id=? AND status='open' AND dispatch_state<>'probe_in_progress' AND version=? AND nonce=? AND reason='startup_stall'`,
		nextNonce, nowMS, nowMS, c.InterruptID, c.ExpectedInterruptVersion, c.Nonce)
	if err != nil {
		return "", "", err
	}
	if n, _ := res.RowsAffected(); n != 1 {
		return "", "", ErrRejectedStale
	}
	// Initial retry event (outcome=retry_pending). It is both the initial
	// command event and the anchor for the pending probe and outcome relation.
	initialEventID, err := persistCommandEventTx(ctx, tx, env, command.OutcomeRetryPending, command.ActionRetry, row.RunID, c.InterruptID, nextNonce, "", nowMS, "")
	if err != nil {
		return "", "", err
	}
	// Pending probe referencing the initial event. The worker runs after commit.
	if _, err := tx.ExecContext(ctx, `INSERT INTO attempt_probes (id,run_id,attempt_no,interrupt_id,state,expected_run_version,expected_generation,requested_by_event_id,created_at_ms) VALUES (?, ?, ?, ?, 'pending', ?, ?, ?, ?)`,
		newID(), row.RunID, row.AttemptNo, c.InterruptID, row.RunVersion, row.Generation, initialEventID, nowMS); err != nil {
		return "", "", err
	}
	if _, err := recordHumanDecisionTx(ctx, tx, RecordHumanDecisionCmd{
		Action: DecisionRetry, CommandEventID: env.EventKey, InterruptID: c.InterruptID, NowMS: nowMS,
	}); err != nil {
		return "", "", err
	}
	return nextNonce, initialEventID, nil
}

// --- persistence helpers ---

func persistCommandEventTx(ctx context.Context, tx *sql.Tx, env command.CommandEventEnvelopeV1, outcome command.CommandOutcome, action command.CommandAction, runID, interruptID, nextNonce, finalForEventID string, nowMS int64, eventID string) (string, error) {
	ev := command.NewEvent(env, outcome, action, runID, interruptID, nextNonce, finalForEventID)
	body, err := ev.CanonicalBytes()
	if err != nil {
		return "", err
	}
	// eventID is pre-generated by the caller when a deterministic effect (Gate
	// re-evaluation operation, command_effects fact) must reference the close
	// event inside the same transaction; otherwise allocate here.
	if eventID == "" {
		eventID = newID()
	}
	idem := command.EventStageKey(env.EventKey, command.StageInitial)
	if _, err := tx.ExecContext(ctx, `INSERT INTO events (id,run_id,project_id,type,source,payload_schema_version,payload_json,idempotency_key,occurred_at_ms,recorded_at_ms) VALUES (?,?,?,'command.event','forge',1,?,?,?,?)`,
		eventID, nullable(runID), env.ProjectID, string(body), idem, nowMS, nowMS); err != nil {
		return "", err
	}
	if outcome == command.OutcomeRetryPending {
		if _, err := tx.ExecContext(ctx, `INSERT INTO command_event_outcomes (id,event_key,initial_event_id,final_event_id,state,created_at_ms,finalized_at_ms) VALUES (?,?,?,NULL,'pending',?,NULL)`,
			newID(), env.EventKey, eventID, nowMS); err != nil {
			return "", err
		}
		return eventID, nil
	}
	// final in one transaction (non-retry: initial == final).
	if _, err := tx.ExecContext(ctx, `INSERT INTO command_event_outcomes (id,event_key,initial_event_id,final_event_id,state,created_at_ms,finalized_at_ms) VALUES (?,?,?,?, 'final', ?, ?)`,
		newID(), env.EventKey, eventID, eventID, nowMS, nowMS); err != nil {
		return "", err
	}
	return eventID, nil
}

func writeCommandAckOpTx(ctx context.Context, tx *sql.Tx, env command.CommandEventEnvelopeV1, outcome command.CommandOutcome, action command.CommandAction, finalEventID, interruptID, runID, nextNonce, ackKey string, nowMS int64) error {
	ev := command.NewEvent(env, outcome, action, runID, interruptID, nextNonce, "")
	ack := command.NewAck(finalEventID, ev)
	body, err := ack.CanonicalBytes()
	if err != nil {
		return err
	}
	op := Operation{Key: ackKey, Kind: OperationCommandAck, Payload: body, InterruptID: interruptID, RunID: runID}
	return insertOperation(ctx, tx, op, runID, interruptID, nowMS)
}

func closeInterruptTx(ctx context.Context, tx *sql.Tx, interruptID string, expectedVersion int64, expectedNonce, closeReason string, nowMS int64) error {
	res, err := tx.ExecContext(ctx, `UPDATE interrupts SET status='closed',close_reason=?,closed_at_ms=?,version=version+1,updated_at_ms=? WHERE id=? AND status='open' AND version=? AND nonce=?`, closeReason, nowMS, nowMS, interruptID, expectedVersion, expectedNonce)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n != 1 {
		return ErrRejectedStale
	}
	return excludeStaleBatchMembersTx(ctx, tx, interruptID, nowMS)
}

func actorName(env command.CommandEventEnvelopeV1) string {
	if env.Actor == nil {
		return ""
	}
	return *env.Actor
}

func newToken() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(fmt.Sprintf("storage: crypto/rand: %v", err))
	}
	return hex.EncodeToString(b[:])
}

func lookupCommandReceiptTx(ctx context.Context, tx *sql.Tx, env command.CommandEventEnvelopeV1) (ApplyCommandEventResult, bool, error) {
	var disposition, domainEventID string
	var outcomeID sql.NullString
	err := tx.QueryRowContext(ctx, `SELECT disposition,domain_event_id,command_outcome_id FROM command_receipts WHERE project_id=? AND event_kind=? AND remote_event_id=?`, env.ProjectID, string(env.Source), env.RemoteEventID).
		Scan(&disposition, &domainEventID, &outcomeID)
	if errors.Is(err, sql.ErrNoRows) {
		return ApplyCommandEventResult{}, false, nil
	}
	if err != nil {
		return ApplyCommandEventResult{}, false, err
	}
	if disposition != "accepted" {
		return ApplyCommandEventResult{Ignored: true}, true, nil
	}
	res := ApplyCommandEventResult{FinalEventID: domainEventID}
	if outcomeID.Valid {
		var state string
		if err := tx.QueryRowContext(ctx, `SELECT state FROM command_event_outcomes WHERE id=?`, outcomeID.String).Scan(&state); err == nil && state == "pending" {
			res.Outcome = command.OutcomeRetryPending
			return res, true, nil
		}
	}
	res.Outcome = command.OutcomeApplied
	return res, true, nil
}

func writeIgnoredCommandReceiptTx(ctx context.Context, tx *sql.Tx, env command.CommandEventEnvelopeV1, disposition string, nowMS int64) error {
	_, err := tx.ExecContext(ctx, `INSERT INTO command_receipts (id,project_id,event_kind,remote_event_id,event_key,target_kind,target_id,actor,raw_digest,disposition,domain_event_id,command_outcome_id,observed_at_ms) VALUES (?,?,?,?,?,?,?,?,?,?,NULL,NULL,?)`,
		newID(), env.ProjectID, string(env.Source), env.RemoteEventID, env.EventKey, string(env.Target.Kind), env.Target.ID, nullablePtr(env.Actor), env.RawDigest, disposition, nowMS)
	return err
}

func writeAcceptedCommandReceiptTx(ctx context.Context, tx *sql.Tx, env command.CommandEventEnvelopeV1, disposition, domainEventID string, nowMS int64) error {
	var outcomeID sql.NullString
	err := tx.QueryRowContext(ctx, `SELECT id FROM command_event_outcomes WHERE event_key=?`, env.EventKey).Scan(&outcomeID)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return err
	}
	_, err = tx.ExecContext(ctx, `INSERT INTO command_receipts (id,project_id,event_kind,remote_event_id,event_key,target_kind,target_id,actor,raw_digest,disposition,domain_event_id,command_outcome_id,observed_at_ms) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
		newID(), env.ProjectID, string(env.Source), env.RemoteEventID, env.EventKey, string(env.Target.Kind), env.Target.ID, nullablePtr(env.Actor), env.RawDigest, disposition, nullable(domainEventID), nullableNullString(outcomeID), nowMS)
	return err
}

func nullablePtr(s *string) any {
	if s == nil {
		return nil
	}
	return *s
}
func nullableNullString(s sql.NullString) any {
	if !s.Valid {
		return nil
	}
	return s.String
}

// startup_stall two-phase result port (specs/command.md §5, ADR-013). The retry
// request is written by ApplyCommandEvent; this port owns the final probe
// result. Probe success is the ADR-013 single CAS: absence evidence, end old
// attempt (retry_after_absence), isolation release, close/responded,
// waiting_human -> queued, final outcome + ack — all-or-nothing. Probe failure
// reuses the same Interrupt, increments version, rotates nonce and emits one
// absence_unconfirmed ack; isolation is retained.

// RetryProbeResultCmd is the input to ApplyRetryProbeResult.
