//go:generate go run ./genschema -out artifacts

// Package schema owns Sift's boundary types, JSON decode gateway, validation
// rules, and generated JSON Schema artifacts. The seed types below fix the
// conventions that every later boundary type (config, control-plane envelope,
// Brain touchpoint I/O, Forge payload) must follow, and they are the subjects
// of the V14 golden suite.
//
// A boundary type declares its contract purely through its struct definition:
//
//   - Required fields are pointers carrying the `sift:"required"` tag.
//   - Optional fields are pointers with `omitempty`.
//   - Closed sets of string values are named types implementing
//     [Enumerated]; EnumValues is the single source for both the
//     runtime membership check and the generated JSON Schema.
//
// The generated JSON Schemas for these types live in artifacts/ and are
// regenerated by `go generate ./...`; the CI drift check fails if they diverge
// from the committed files.
package schema

// Mode marker types. A boundary struct embeds exactly one of these to
// declare its decode mode at the type level; the schema generator reads the
// embedded marker rather than a separate registration, so a type's contract
// shape is defined in one place. They carry no fields and are excluded from
// JSON via `json:"-"`.

// ClosedType is embedded by structs decoded in [Closed] mode.
type ClosedType struct{}

// OpenEnvelopeType is embedded by structs decoded in [OpenEnvelope]
// mode.
type OpenEnvelopeType struct{}

// Severity is the closed severity enum used across attention/interrupt
// contracts (config.md §3.9).
type Severity string

const (
	SeverityLow    Severity = "low"
	SeverityNormal Severity = "normal"
	SeverityHigh   Severity = "high"
)

// EnumValues satisfies [Enumerated]. It is the single source for the
// allowed severity set.
func (Severity) EnumValues() []string {
	return []string{string(SeverityLow), string(SeverityNormal), string(SeverityHigh)}
}

// ForgeIssueState is the subset of a Forge issue/change lifecycle that Sift
// consumes. This slice exercises the two states the adapter depends on; the
// full lifecycle (including an Unknown state for values the adapter cannot
// determine) lands with the Forge adapter slice.
type ForgeIssueState string

const (
	ForgeIssueOpen   ForgeIssueState = "open"
	ForgeIssueClosed ForgeIssueState = "closed"
)

// EnumValues satisfies [Enumerated].
func (ForgeIssueState) EnumValues() []string {
	return []string{string(ForgeIssueOpen), string(ForgeIssueClosed)}
}

// ClosedExample is the canonical closed-contract type. Config fragments, LLM
// touchpoint outputs and control-plane request params follow this shape: every
// field is owned by Sift, so an unknown field is rejected and every required
// field must be present and well-typed.
//
// It is decoded with [Closed]. The schema generator emits
// additionalProperties:false for it.
type ClosedExample struct {
	ClosedType `json:"-"`

	Name     *string   `json:"name" sift:"required"`
	Severity *Severity `json:"severity" sift:"required"`
	// Timeout is optional; absent is valid and distinct from an empty value.
	Timeout *string `json:"timeout,omitempty"`
}

// OpenEnvelopeExample is the canonical open-envelope type. Forge payloads and
// the LLM provider outer envelope follow this shape: upstream may add fields
// the adapter does not consume (accepted for forward compatibility), but the
// consumed fields keep required/type/enum rules.
//
// It is decoded with [OpenEnvelope]. The schema generator omits
// additionalProperties:false for it, so extra fields are allowed.
type OpenEnvelopeExample struct {
	OpenEnvelopeType `json:"-"`

	// Number mirrors a forge issue/change number; an integer, not a free
	// string.
	Number *int             `json:"number" sift:"required"`
	Title  *string          `json:"title" sift:"required"`
	State  *ForgeIssueState `json:"state" sift:"required"`
	// Author is the issue actor handle. It is optional here only to exercise
	// the optional-pointer convention; the real Forge adapter treats a missing
	// actor on a driving event as fail-closed (H9), enforced in its own slice.
	Author *string `json:"author,omitempty"`
}
